---
title: "R Notebook"
output: html_notebook
---


# Setup
```{r Load packages}
library(ggplot2)
library(viridis)
library(tidyverse)

#install.packages('extrafont')
library(extrafont)

#install.packages('Rttf2pt1') 
library(Rttf2pt1)
loadfonts()

library('scales')

```


```{r Load Data}

combined_country <- read_csv(file = "../data/clean_data/combined_tidy.csv")
```




```{r Set Theme}

font_family <- "Helvetica"  #Futura-Medium 


#base_family=font_family, #could use instead
newtheme <- theme_bw(base_family = font_family, base_size = 12) + 
  theme(plot.title = element_text(color = "#0d4459",  size = 14),
        axis.title.x = element_text(size = 10),
       axis.title.y = element_text(size = 10),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        panel.grid.major.y = element_line(colour = "#D8D8D8"), panel.grid.minor.y = element_blank(), 
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(), 
        panel.border = element_blank(), panel.background = element_blank(),  #element_rect(color = "black", size = 1)  #used for border around plot
        legend.position = "bottom", legend.key = element_rect(fill = "#FFFFFF00"),
        complete = FALSE
        )

#color template
cols <- c("#0d4459", "#00a990", "#d05527", "#a33332", "#b2b2b1", "#dfb9a6")
  
```


# Graphs
```{r Test Line }
test <- combined_country %>%
  filter(inc_group_16 !="..",   #omits countries w/o income group - e.g. British Virgin Islands
           major_group != "Former Soviet Union") %>%  #omit USSR and former USSR
  group_by(year, inc_group_16) %>%
  summarize(tot = sum(area, na.rm = T))
#omits NA's - currently Czechoslovakia, Falkland Islands (Malvinas), French Guiana, Guadeloupe, Martinique, Mayotte, Montserrat, Niue, Norfolk Island, Pacific Islands Trust Territory, Réunion, Saint Helena 

#create df with baseline pasture area (1961 area)
temp <- test %>% filter(year==1961) %>% ungroup() %>% select(inc_group_16, "baseline"=tot) 

#merge with pasture area by income group and subtract to get change since baseline
pd <- left_join(filter(test), temp) %>%
  mutate(change=tot-baseline)


#create graph
p <- ggplot(pd) +
  geom_line(aes(x=year, y=change/1000000, color = inc_group_16)) +                               #data to plot & variable to group by
  labs(x="Year",                                                                                 # x axis title
       y="Change in Pasture Area (Mha)",                                                                   # y  axis title
       title = "Fig 1) Pasture Rose for Upper-Middle and \nFell for High Income Countries Since 1961" # figure title
       ) +  
  newtheme +
  scale_color_manual(values=cols,
                     name ="Income Group",
                     breaks=c("H", "UM", "LM", "L"),
                     labels=c("High", "Upper-Middle", "Lower-Middle", "Low"))

#p
ggsave(filename = "../outputs/test_line_graph.pdf", p, width = 6, height = 6, family=font_family)
embed_fonts("../outputs/test_line_graph.pdf", outfile="../outputs/test_line_graph_Futura_Hv_BT.pdf")
```

```{r Test Pie}
#create dataframe of pasture area by major region for 2016
pd <- combined_country %>%
  filter(inc_group_16 !="..",  
           major_group != "Former Soviet Union", 
         year==2016) %>%  
  group_by(major_group) %>%
  summarize(tot = sum(area, na.rm = T), pct <- tot/sum(tot))

global_area=sum(pd$tot)

pd$share=pd$tot/global_area
#create graph
p <- ggplot(pd, aes(x="", y=share, fill = major_group)) + 
   geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) + geom_text(aes(label = paste0(round(share*100), "%")), position = position_stack(vjust = 0.5))+
  labs(x = NULL, y = NULL, fill = NULL, title = "Fig 2) Africa Has the Greatest Share of Pasture") +  
  newtheme +
  scale_fill_manual(values=cols)+
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = 0.5),
        panel.grid.major.y = element_blank())

p
ggsave(filename = "../outputs/test_pie_graph.pdf", p, width = 6, height = 6)
```

```{r Test Bar Chart}
#create dataframe of pasture area by major region for 2016
pd <- combined_country %>%
  filter(inc_group_16 !="..",  
           major_group != "Former Soviet Union", 
         year==2016) %>%  
  group_by(major_group) %>%
  summarize(tot = sum(area, na.rm = T))

#create graph
p <- ggplot(pd, aes(x=reorder(major_group, tot), y=tot/1000000, fill = major_group)) + 
   geom_col(position="dodge") +
  labs(title = "Fig 3) Africa Has the Greatest Share of Pasture",
       x="", y="Million Hectares (Mha)"
       ) +  
  newtheme +
  theme(legend.title=element_blank(),
        legend.position = "none",
        axis.ticks = element_blank())+
  scale_y_continuous(labels = format_format(big.mark = ",", decimal.mark = ".", scientific = FALSE))+
  scale_fill_manual(values=cols)

p
ggsave(filename = "../outputs/test_bar_graph.pdf", p, width = 6, height = 6)
```





